version: "3"
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a
  web:
    build: .
    command: >
      bash -c "
        bundle exec rails s -p 3000 -b '0.0.0.0';
        bundle exec rails db:migrate RAILS_ENV=development;
      "
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
