name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" , "docker"]
  pull_request:
    branches: [ "main", "docker" ]
jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
    - name: checkout pushed commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: run test on docker-compose
      run: |
        COMPOSE_DOCKER_CLI_BUILD=1 docker-compose up --build
        wait-for-it.sh db:3306 -- docker-compose run --rm web bin/setup && docker-compose run --rm web rails test
