name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
    - name: checkout pushed commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
#         node-version: '16'
    - name: run test on docker-compose
      run: |
        docker-compose build --no-cache
        docker-compose up 
        docker-compose run --rm web bin/setup
        docker-compose run --rm web rails test
    - name: Compile with Webpacker
      run: |
        yarn upgrade
        bundle exec rake webpacker:compile
      env:
        NODE_ENV: test 
